# Generated by Django 5.2.4 on 2025-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacad',
            field=models.BooleanField(default=False),
        ),
    ]
