# Generated by Django 5.2.4 on 2025-07-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_destacad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='destacad',
            new_name='destacado',
        ),
    ]
