# Generated by Django 5.2.4 on 2025-07-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_direccion_remove_perfil_es_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
